export const level2 = [
  'W W W W W W W W W W W W W W W W W W W W',
  'W       W                       W     W',
  'W   E   W           E           E     W',
  'W       W  E                          W',
  'W       W          E          W W W W W',
  'W               W         W           W',
  'W               W   E                 W',
  'W         E E   W               E     W',
  'W               W                     W',
  'W W W W     W W W W W W W W     W   E W',
  'W                         W           W',
  'W     E     E             W     E     W',
  'W                   E     W           W',
  'W W W W W W W             W           W',
  'W       W                 W           W',
  'W       W  E          W W W W     W W W',
  'W   P   W                 W           W',
  'W                   E                 W',
  'W         W W W                   E   W',
  'W           W       E                 W',
  'W W W W W W W W W W W W W W W W W W W W'
];