export const level3 = [
  'W W W W W W W W W W W W W W W W W W W W',
  'W                 W                   W',
  'W   A E     E     W     E    E    A   W',
  'W                 W       E           W',
  'W                                     W',
  'W W W W W W           W   H     W     W',
  'W         W     W                     W',
  'W   E     W     W     E               W',
  'W               W                     W',
  'W W W W         W W W W W W           W',
  'W   E        E  W         W     E     W',
  'W                     E   W           W',
  'W       E                 W           W',
  'W               W         W     W     W',
  'W               W     E   W           W',
  'W W W W W W W W W         W W W       W',
  'W   E     E                           W',
  'W                   E         P       W',
  'W   A   E       W         W           W',
  'W               W     E   W           W',
  'W W W W W W W W W W W W W W W W W W W W'
];