export const level4 = [
  'W W W W W W W W W W W W W W W W W W W W',
  'W                 W           W       W',
  'W A   W   E   E   W     E     W   E   W',
  'W     W           W           W       W',
  'W   H     E       W     E     W   E   W',
  'W                 W                   W',
  'W   E                                 W',
  'W                   E   W     W       W',
  'W         W W W W W           W       W',
  'W   E             W           W   E   W',
  'W            A    W           W       W',
  'W   E             W     E     W     W W',
  'W         W W W W W                   W',
  'W   E                   W             W',
  'W             W               W   H   W',
  'W       W           W W W W W W       W',
  'W W W W W   E E     W               E W',
  'W                   W     A     W     W',
  'W P         W       W     A     W   E W',
  'W                   W           W     W',
  'W W W W W W W W W W W W W W W W W W W W'
];