export const level5 = [
  'W W W W W W W W W W W W W W W W W W W W W W W W W',
  'W                                               W',
  'W     E       E       A     E     H             W',
  'W                   W W W             E     E   W',
  'W   E                             W       W     W',
  'W     W W     E                                 W',
  'W                   W W W             E     H   W',
  'W     A       E     W             E             W',
  'W                       H           H     W     W',
  'W       W     W W W               W       W     W',
  'W   E   W         W   E   W   E   W   E   W     W',
  'W       W     A   W       W       W             W',
  'W W W W W     W W W W W W W W W W W       W W W W',
  'W       W     W                   W             W',
  'W   E   W     W   A               W       W     W',
  'W       W             W W                 W     W',
  'W             E       W W                       W',
  'W     W     W     E             W     E     E   W',
  'W           W                   W               W',
  'W   E       W W W W W W W W W W W W W W     W W W',
  'W                                 W             W',
  'W   E       W W W W W       A     W   A         W',
  'W                   W   E   A     W       P     W',
  'W             H     W             W             W',
  'W W W W W W W W W W W W W W W W W W W W W W W W W'
];